{% set name = "ittapi" %}
{% set version = "3.25.3" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://github.com/intel/{{ name }}/archive/refs/tags/v{{ version }}.zip
  sha256: b862c0c5eba4f0251cd5ee8c1e86befa40a6ef9f9a44942f31951ebb059a6dbf

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}  # [not win]
    - {{ stdlib("c") }}
    - cmake
    - make  # [linux]

outputs:
  - name: {{ name|lower }}-static
    version: {{ version }}
    script: install.sh   # [unix]
    script: install.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}  # [not win]
        - {{ stdlib("c") }}
        - cmake
        - make  # [linux]
    test:
      commands:
        - dir %LIBRARY_LIB%\libittnotify.lib  # [win]
        - dir %LIBRARY_INC%\ittnotify.h  # [win]
        - test -f ${PREFIX}/lib/libittnotify.a  # [not win]
        - test -f ${PREFIX}/include/ittnotify.h  # [not win]
    about:
      summary: Static C-Library of Intel® ITT/JIT API

  - name: {{ name|lower }}
    version: {{ version }}
    script: install.sh   # [unix]
    script: install.bat  # [win]
    build:
      skip: True  # [osx]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}  # [not win]
        - {{ stdlib("c") }}
        - cmake
        - make  # [linux]
      host:
        - {{ pin_subpackage(name|lower ~ '-static', exact=True) }}
        - python
        - setuptools >=61.0
        - pip
      run:
        - {{ pin_subpackage(name|lower ~ '-static', exact=True) }}
        - python
    test:
      source_files:
        - python/utest  # [not osx]
      imports:
        - ittapi  # [not osx]
      commands:
        - pip check
        - pytest ./python/utest  # [not osx]
      requires:
        - pip
        - pytest  # [not osx]
    about:
      summary: Python bindings to Intel® ITT/JIT API

about:
  home: https://github.com/intel/ittapi
  license: GPL-2.0-only OR BSD-3-Clause
  license_file:
    - BSD-3-Clause.txt
    - GPL-2.0-only.txt
  summary: Intel® Instrumentation and Tracing Technology (ITT) and Just-In-Time (JIT) API
  description: |
    This ITT/JIT open source profiling API includes:
      - Instrumentation and Tracing Technology (ITT) API
      - Just-In-Time (JIT) Profiling API

    The Instrumentation and Tracing Technology (ITT) API enables your application to generate and control the collection of trace data during its execution across different Intel tools.

    ITT API consists of two parts: a static part and a dynamic part. The dynamic part is specific for a tool and distributed only with a particular tool. The static part is a common part shared between tools. Currently, the static part of ITT API is distributed as a static library and released under a BSD/GPLv2 dual license with every tool supporting ITT API.
  doc_url: https://github.com/intel/ittapi
  dev_url: https://github.com/intel/ittapi

extra:
  recipe-maintainers:
    - eparshut
    - ekovanova
